POST http://localhost:8080/users
content-type: application/json

{
  "username": "pedroht",
  "name": "Pedro Henrique",
  "password": "1234"
}

###

POST http://localhost:8080/tasks
content-type: application/json
Authorization: Basic cGVkcm9odDoxMjM0

{
  "title": "Este título deve salvar.",
  "description": "Essa é a descrição da tarefa",
  "startAt": "2026-03-13T20:50:23",
  "endAt": "2026-03-14T17:50:23",
  "priority": "HIGH"
}